---
apiVersion: v1
kind: Namespace
metadata:
  name: nweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nielsweb
  name: nielsweb
  namespace: nweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nielsweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nielsweb
    spec:
      containers:
      - image: nielae/personal
        name: nipersonal
        resources: {}
        ports:
        - containerPort: 80
          name: nielsweb
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nielsweb
  name: nielsweb
  namespace: nweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nielsweb
  type: LoadBalancer
status:
  loadBalancer: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: nweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:15-alpine
        name: nielasdb
        env:
        - name: POSTGRES_USER
          value: niela
        - name: POSTGRES_PASSWORD
          value: niela
        ports:
        - containerPort: 5432
          name: nielasdb
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: nweb
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: db
